### ISSUE TITLE
Change .light to .fan

### ISSUE THREAD

**Issue by nv96** [hubertjanhickinson/OrconWifiController#5]
Code for changing the `light.orcon_unit_speed` entity from a light to a fan.
This code needs to be in your `/homeassistant/configuration.yaml` file.
```

fan:
  - platform: template
    fans:
      afzuiging_fan:
        friendly_name: "Mechanische ventilatie"
        value_template: "{{ states('light.orcon_unit_speed') }}"
        percentage_template: >
          {{ (state_attr('light.orcon_unit_speed', 'brightness') / 255 * 100) | int }}
        turn_on:
          service: homeassistant.turn_on
          entity_id: light.orcon_unit_speed
        turn_off:
          service: homeassistant.turn_off
          entity_id: light.orcon_unit_speed
        set_percentage:
          service: light.turn_on
          entity_id: light.orcon_unit_speed
          data_template:
            brightness: >
              {{ ( percentage / 100 * 255) | int }} 
        speed_count: 3   
```
